# Generated by Django 4.2.4 on 2023-08-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('creditor_name', models.CharField(max_length=100)),
                ('company_suied', models.CharField(max_length=100)),
                ('company_phone', models.CharField(max_length=20)),
                ('folder_id', models.CharField(max_length=100)),
                ('airtable_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
    ]
