# Generated by Django 4.2.4 on 2023-08-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='company_phone',
        ),
        migrations.AddField(
            model_name='lead',
            name='business_address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='county',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='airtable_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='company_suied',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='creditor_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='folder_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
