# Generated by Django 4.2.4 on 2023-08-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_remove_lead_company_phone_lead_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date',
            field=models.CharField(default='', max_length=50),
        ),
    ]
