# Generated by Django 4.2.4 on 2023-08-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_lead_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='business_address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
