# Generated by Django 4.2.4 on 2023-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_lead_business_address_alter_lead_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('log', models.CharField(max_length=200)),
            ],
        ),
    ]
